Traceback (most recent call last):
  File "test-data-2.0/failing/testTypesDict4.py", line 14, in <module>
    bar({'y': func})  # error
  File "test-data-2.0/failing/testTypesDict4.py", line 11, in bar
    return foo(d)
  File "test-data-2.0/failing/testTypesDict4.py", line 8, in foo
    return res

WyppTypeError: [42, 'x']

RÃ¼ckgabewert vom Typ `list[str]` erwartet bei Aufruf der Funktion `foo`.

## Datei test-data-2.0/failing/testTypesDict4.py
## RÃ¼ckgabetyp deklariert in Zeile 3:

def foo(d: dict[str, Callable[[], str]]) -> [0;31m[1mlist[str][0;0m:

## Fehlerhaftes return in Zeile 8:

    return res

## Aufruf in Zeile 11 verursacht das fehlerhafte return:

    return [0;31m[1mfoo(d)[0;0m