Traceback (most recent call last):
  File "file-test-data/extras/testTypesProtos4.py", line 27, in <module>
    print(foo(ConcreteWrong()))
  File "file-test-data/extras/testTypesProtos4.py", line 24, in foo
    return fn(2)
  File "file-test-data/extras/testTypesProtos4.py", line 20, in <lambda>
    return lambda x: bar(x) # invalid call of bar with argument of type int

WyppTypeError: 2

Der Aufruf der Funktion `bar` erwartet einen Wert vom Typ `str` als erstes Argument.
Aber der Ã¼bergebene Wert hat den Typ `int`.

## Datei file-test-data/extras/testTypesProtos4.py
## Fehlerhafter Aufruf in Zeile 20:

        return lambda x: bar([0;31m[1mx[0;0m) # invalid call of bar with argument of type int

## Typ deklariert in Zeile 15:

def bar([0;31m[1ms: str[0;0m) -> int: