Traceback (most recent call last):
  File "file-test-data/extras/testWrongKeywordArg.py", line 4, in <module>
    foo(x=4)

WyppTypeError: unbekanntes Schlüsselwort-Argument

Funktion `foo` akzeptiert kein Schlüsselwort-Argument `x`.

## Datei file-test-data/extras/testWrongKeywordArg.py
## Fehlerhafter Aufruf in Zeile 4:

foo(x=4)